#!/bin/sh
cd app/


docker build -t "noname_app:$(date +%y%m%d)" --build-arg CACHEBUST=$(date +%s) .
cd ..
cd nginx/
docker build -t "nginx:latest" .
cd ..
docker run -dP --name magritapp "noname_app:latest"
docker run --publish "80:80" -it --name nginx --link magritapp:magritapp nginx
