#!/bin/bash

if [ "$1" == "install" ]
then
	cd /tmp/
	mkdir magritapp
	git clone http://github.com/mthh/magrit
	cp -r magrit/misc/Docker/ magritapp/
	cp -r magrit/noname_app/static/ magritapp/Docker/nginx/
	cd magritapp/Docker
	cd app/
	docker build -t "magrit_app:$(date +%y%m%d)" --build-arg CACHEBUST=$(date +%s) .
	cd ..
	cd nginx/
	docker build -t "nginx:latest" .
	cd ..
	docker run -dP --name magritapp "magrit_app:$(date +%y%m%d)"
	docker run --publish "80:80" -dP --name nginx --link magritapp:magritapp nginx
elif [ "$1" == "update" ]
then
	cd /tmp
	rm -rf magrit
	rm -rf magritapp/Docker/nginx/static
	git clone http://github.com/mthh/magrit
	cp -r magrit/noname_app/static/ magritapp/Docker/nginx/
	cd magritapp/Docker/nginx/
	docker build -t "nginx:latest" .
	cd ../app
	docker build -t "magrit_app:$(date +%y%m%d)" --build-arg CACHEBUST=$(date +%s) .
	cd ..
	docker kill magritapp nginx && docker rm magritapp nginx
	docker run -dP --name magritapp "magrit_app:$(date +%y%m%d)"
	docker run --publish "80:80" -dP --name nginx --link magritapp:magritapp nginx
fi
